# Generated by Django 4.2.4 on 2025-04-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_BRASFI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
