# Generated by Django 5.2 on 2025-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_BRASFI', '0005_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_per_question',
            field=models.IntegerField(default=20),
        ),
    ]
