# Generated by Django 5.2 on 2025-05-13 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_BRASFI', '0007_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact_area', models.CharField(choices=[('educacao', 'Educação'), ('meio_ambiente', 'Meio Ambiente'), ('saude', 'Saúde'), ('tecnologia', 'Tecnologia'), ('outros', 'Outros')], max_length=30)),
                ('objective', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
